# Generated by Django 5.1 on 2025-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('wind_degrees', models.IntegerField()),
            ],
        ),
    ]
