# Generated by Django 5.1 on 2025-02-17 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
