# Generated by Django 5.1 on 2025-02-17 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0003_weather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
