# Generated by Django 5.1 on 2025-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0004_alter_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
