# Generated by Django 5.1 on 2025-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0005_weather_description_weather_feels_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='icon',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
