# Generated by Django 5.1 on 2025-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0006_weather_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
