# Generated by Django 5.1 on 2025-02-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0008_alter_weather_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='50d', max_length=20, null=True),
        ),
    ]
