# Generated by Django 5.1 on 2025-02-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0009_alter_weather_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='50n', max_length=20),
        ),
    ]
