# Generated by Django 5.1 on 2025-04-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0010_alter_weather_description_alter_weather_feels_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zodiacsign',
            name='svg',
        ),
    ]
