# Generated by Django 5.1 on 2025-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0011_remove_zodiacsign_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
