# Generated by Django 5.2 on 2025-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0012_zodiacsign_description_zodiacsign_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zodiacsign',
            name='last_updated',
        ),
    ]
