# Generated by Django 5.2 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac_app', '0013_remove_zodiacsign_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiacsign',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
