
services:
  db:
    image: postgres:13
    hostname: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: uvicorn zodiac.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/zodiac
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
